#! /bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_FONT_FAMILY="Terminus:size=9"
ICON_FONT="FontAwesome:size=10"
#ICON_FONT2="fontcustom:size=10"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

#clock
while true;
	do
		echo 'C' $(date +"%H:%M");
	sleep 5;
done > "$PANEL_FIFO" &

# date
while true;
do echo 'D' $(date +'%b %d')
	sleep 5
done > $PANEL_FIFO &

# alsa volume
while true;
do
ALSA_VOLUME=$(amixer get Master | grep 'Mono: Playback' | grep -o '...%' | sed 's/\[//' | sed 's/%//' | sed 's/ //')
ALSA_STATE=$(amixer get Master | grep 'Mono: Playback' | grep -o '\[on]')
if [ $ALSA_STATE ]
	then
	if [ $ALSA_VOLUME -ge 70 ]
		then
			echo V'' $ALSA_VOLUME
		fi
	if [ $ALSA_VOLUME -gt 0 -a $ALSA_VOLUME -lt 70 ]
	then
		echo V'' $ALSA_VOLUME
	fi
	if [ $ALSA_VOLUME -eq 0 ]
	then
		echo V'' $ALSA_VOLUME
	fi
	else
		echo V'' $ALSA_VOLUME
	fi
	sleep 0.1
done > $PANEL_FIFO &

# mpc

while true;
do
	SONG_NAME=$(mpc | head -n1)
	if [[ -n $(mpc status | grep paused) ]]
	then
		echo "R%{T3}%{A:mpc prev:}%{A}  %{A:mpc play:}%{A}  %{A:mpc next:}%{A}%{T1} $SONG_NAME"
	else
		echo "R%{T3}%{A:mpc prev:}%{A}  %{A:mpc pause:}%{A}  %{A:mpc next:}%{A}%{T1} $SONG_NAME"
	fi

	sleep 1
done > $PANEL_FIFO &

# power 
echo P'' > $PANEL_FIFO &

. panel_colors



cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -u 2 | sh &

wait
